on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: caneesh/string-replace@master
      with:
        who-to-greet: 'Mona the Octocat'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
    - name: Replace String
    run: |
      branch="caneEsh/my/BRANCHname"
      branch=`echo  ${branch//\//_} | tr '[:upper:]' '[:lower:]'`
      echo $branch